#!/usr/bin/env python

import sys
import os


def main ():
  img = sys.argv[1].split (".")[0]
  cmd = "convert " + sys.argv[1] + " -resize 24x24 " + img + ".png"
  os.system (cmd)

if __name__ == '__main__':
  main ()
